services:
  postgres:
    image: postgres:11.8
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
    volumes:
      - ./testdata/pg/:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  oracle:
    image: gvenzl/oracle-free:23-slim-faststart
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: test
    volumes:
      - ./testdata/oracle/:/grackle-initdb.d/
      - ./modules/doobie-oracle/src/test/resources/scripts/:/container-entrypoint-initdb.d/
    healthcheck:
      test: bash -c "[ -f /tmp/healthy ]"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: Test_123_Test
      MSSQL_PID: Developer
      ACCEPT_EULA: Y
      MSSQL_TCP_PORT: 1433
    volumes:
      - ./testdata/mssql/:/grackle-initdb.d/
      - ./modules/doobie-mssql/src/test/resources/scripts/:/container-entrypoint-initdb.d/
    entrypoint: ["/bin/bash", "/container-entrypoint-initdb.d/entrypoint.sh"]
    healthcheck:
      test: bash -c "[ -f /tmp/healthy ]"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 5s
      start_interval: 5s
